language: cpp
compiler: g++
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:mhier/libboost-latest'

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get update
  - sudo apt-get install -y g++-8 libboost1.70-dev libgmp-dev libssl-dev libntl-dev
  # Install a recent CMake
  - mkdir $HOME/prefix
  - export PATH="$HOME/prefix/bin:$PATH"
  - wget https://cmake.org/files/v3.15/cmake-3.15.2-Linux-x86_64.sh -O cmake_install.sh
  - chmod +x cmake_install.sh
  - ./cmake_install.sh --prefix=$HOME/prefix --exclude-subdir --skip-license

script:
  - mkdir build_debug
  - cd build_debug
  - CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake -DCMAKE_BUILD_TYPE=Debug -DPSI_ANALYTICS_BUILD_TESTS=ON -j 2 ..
  - make -j 5
  - ./bin/psi_analytics_eurocrypt19_test --gtest_filter='-*2_20*'

notifications:
  - email: false
