language: cpp

addons:
  apt:
    packages:
      - cmake
      - cmake-data

compiler:
  - clang
  - gcc

env:
  # Default configuration
  - CONFIG="-DSEED= -DBENCH=0" TEST=""
  # Dynamic allocation
  - CONFIG="-DALLOC=DYNAMIC -DSEED= -DBENCH=0" TEST=""
  # Build for Edwards curves
  - CONFIG="-DSEED= -DBENCH=0 -DFP_PRIME=255 -FP_QNRES=FALSE -DEC_METHD=EDDIE -DED_METHD='PROJC;LWNAF;LWNAF;BASIC'" TEST="-E test_bn|test_fp|test_ed|test_ec|test_cp"

script:
  - mkdir build && cd build
  - cmake $CONFIG  .. && make -j && ctest -V $TEST
  - cd .. && rm -rf build
